Document: rubygems-appscale
Title: Debian rubygems-appscale Manual
Author: <insert document author here>
Abstract: This manual describes what rubygems-appscale is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/rubygems-appscale/rubygems-appscale.sgml.gz

Format: postscript
Files: /usr/share/doc/rubygems-appscale/rubygems-appscale.ps.gz

Format: text
Files: /usr/share/doc/rubygems-appscale/rubygems-appscale.text.gz

Format: HTML
Index: /usr/share/doc/rubygems-appscale/html/index.html
Files: /usr/share/doc/rubygems-appscale/html/*.html
